### ISSUE TITLE
[ERROR] [1615815069.400621665] [D415Node]: An exception has been thrown: null pointer passed for argument "f"

### ISSUE THREAD

**Issue by SimonOuyang7386** [jdgalviss/realsense_ros2#6]
I revise some codes in rs_d435_node.cpp to fit realsense d415, I run the command "ros2 run realsense_ros2 rs_d415_node" and get this error. Can anyone teach me how to do to fit the realsense d415 in this example, thanks.
[rs_d415_node.zip](https://github.com/jdgalviss/realsense_ros2/files/6141849/rs_d415_node.zip)

**Comment by jdgalviss** [comment]
I don't have the realsense d415 to test it. I developed the node exclusively for realsense d435. Unfortunately, these stereo-cameras usually present compatibility issues with each other.

**Comment by jdgalviss** [comment]
I will close this issue since d415 is out of the scope of the repo. If any issues are found with the d435 or t264 nodes please reopen.
