### ISSUE TITLE
Unsuccessful build of the repo on Jetson Nano

### ISSUE THREAD

**Issue by nima-negarandeh** [jdgalviss/realsense_ros2#7]
I tried to build the repo on my device, but the process was not successful.
I'm using Jetson Nano hardware, [Xubuntu 20.04 for Jetson Nano](https://forums.developer.nvidia.com/t/xubuntu-20-04-focal-fossa-l4t-r32-3-1-custom-image-for-the-jetson-nano/121768), and ROS foxy.
The following lines demonstrate the terminal log during the process.

```
ap@ap-desktop:~/real_ws$ colcon build
Starting >>> realsense_ros2
[Processing: realsense_ros2]                             
--- stderr: realsense_ros2                                
In file included from /home/apeiron/real_ws/src/realsense_ros2/realsense_ros2/src/rs_d435_node.cpp:21:
/opt/ros/foxy/include/image_transport/image_transport.h:41:89: note: #pragma message: Warning: This header is deprecated. Use 'image_transport.hpp' instead
   41 | This header is deprecated. Use 'image_transport.hpp' instead")
      |                                                              ^

---
Finished <<< realsense_ros2 [53.9s]
                      
Summary: 1 package finished [54.6s]
  1 package had stderr output: realsense_ros2
```

**Comment by MarcoAndrade26** [comment]
I am having the same issue

**Comment by MarcoAndrade26** [comment]
Hello @NimaNGRD I just solved it by opening the file located in realsense_ros2/realsense_ros2/src/rs_d435_node.cpp and look for image_transport.h and change it for image_transport.hpp.

Save and close the file and then use colcon build.

**Comment by jdgalviss** [comment]
Hello @NimaNGRD . I believe this msg is a warning and it shouldn't stop the package's compilation. So it should still work. Anyways, if you want to get rid of the warning msg, you can replace image_transport.h by image_transport.hpp as @MarcoAndrade26  suggested.

@MarcoAndrade26 thanks for pointing out the solution for the warning. 

If this is working, I will close the issue. Thanks

**Comment by nima-negarandeh** [comment]
Hello @MarcoAndrade26,
Thank you so much. Your solution solved the problem and the package was built successfully.
However, I reached a warning when I try to run 
`ros2 run realsense_ros2 rs_d435_node --ros-args -p is_color:=true -p publish_depth:=true -p fps:=30`
or the following launch files that include the D435 camera.
Could you run all the nodes without any problem?
Do you also use Jetson Nano? If yes, I appreciate it if you tell me the version of librealsense SDK that you are using.

**Comment by nima-negarandeh** [comment]
Hello @jdgalviss,
Thank you for your response.
When I try to run the following node, I recieve warnings and cannot see any of topics in rviz2.
`~/real_ws$ ros2 run realsense_ros2 rs_d435_node --ros-args -p is_color:=true -p publish_depth:=true -p fps:=15
starting rs_d435 node
[INFO] [1630235712.690903191] [D435Node]: Device set up
[INFO] [1630235712.691156946] [D435Node]: 

Module name: Stereo Module
[INFO] [1630235712.730648231] [D435Node]: 

Module name: RGB Camera
[INFO] [1630235712.777563262] [D435Node]: RGB Camera stream is enabled - width: 640, height: 480, fps: 15
[INFO] [1630235713.174500408] [D435Node]: Capture Pipeline started!
Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
         at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
         at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
         at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
         at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
         at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
         at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
         at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
         at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
         at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
         at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
         at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
         at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
         at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp`
Actually, this issue appers in all the launch files that involve the D435 camera.
Would you please help me with this problem?

**Comment by MarcoAndrade26** [comment]
@NimaNGRD I am using Nvidia Xavier AGX. 
I am also getting that error. But I believe that is because T265 node is not running. So "doom" is used to create the transformation for the D435 camera.

Have you already installed rtabmap and rtabmap_ros?

I am getting into some trouble while compiling it.

@jdgalviss Do you have a tutorial showing how you install, build and launch everything?

**Comment by MarcoAndrade26** [comment]
> Hello @MarcoAndrade26,
> Thank you so much. Your solution solved the problem and the package was built successfully.
> However, I reached a warning when I try to run
> `ros2 run realsense_ros2 rs_d435_node --ros-args -p is_color:=true -p publish_depth:=true -p fps:=30`
> or the following launch files that include the D435 camera.
> Could you run all the nodes without any problem?
> Do you also use Jetson Nano? If yes, I appreciate it if you tell me the version of librealsense SDK that you are using.

I am using Intel Realsense Viewer v2.48.0

This is what I used to install it.

`git clone -b debian/foxy/focal/librealsense2 https://github.com/IntelRealSense/librealsense2-release`
`mkdir build && cd build`
`cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=true -DBUILD_GRAPHICAL_EXAMPLES=true -DBUILD_WITH_CUDA=true`
`sudo make uninstall && make clean && make && sudo make install`
`sudo cp config/99-realsense-libusb.rules /etc/udev/rules.d/`
`sudo apt-get install ros-foxy-realsense2-camera ros-foxy-realsense2-description -y`
`sudo apt install openjdk-8-jdk`

If you want, send me a whatsapp: +52 55 4834 8535

**Comment by jdgalviss** [comment]
> Hello @jdgalviss,
> Thank you for your response.
> When I try to run the following node, I recieve warnings and cannot see any of topics in rviz2.
> `~/real_ws$ ros2 run realsense_ros2 rs_d435_node --ros-args -p is_color:=true -p publish_depth:=true -p fps:=15
> starting rs_d435 node
> [INFO] [1630235712.690903191] [D435Node]: Device set up
> [INFO] [1630235712.691156946] [D435Node]:
> 
> Module name: Stereo Module
> [INFO] [1630235712.730648231] [D435Node]:
> 
> Module name: RGB Camera
> [INFO] [1630235712.777563262] [D435Node]: RGB Camera stream is enabled - width: 640, height: 480, fps: 15
> [INFO] [1630235713.174500408] [D435Node]: Capture Pipeline started!
> Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp`
> Actually, this issue appers in all the launch files that involve the D435 camera.
> Would you please help me with this problem?

@NimaNGRD The reason why you are getting this warning is that I did this repo specifically tailored to one project I was developing in which I needed to make sure the transform odom->base_link was available before publishing anything. The easy workaround to this is to comment this line on the rs_d435_node.cpp file: 

// while (!tf_buffer_.canTransform("odom", "base_link", tf2::TimePointZero, 10s))
    // {
    // };

I will push this modification to master because it makes more sense for anyone who wants to use the code. 

@MarcoAndrade26 I haven't tested rtabmap in a while so there is a chance the integration is broken. I will have a look in the next days. But initially, I just followed the indications in the official ros2 repo. It didn't work very well on the Jetson Nano if I remember well. The results you see in this repo were obtained by recording a rosbag and then running rtabmap on a PC. I hope that helps.

If you find anything that needs to be modified, feel free to create a PR and I will review it as soon as I can.

**Comment by MarcoAndrade26** [comment]
Thanks! @jdgalviss There is an issue opened [here](https://github.com/introlab/rtabmap_ros/issues/613).

in my workspace:

git clone https://github.com/introlab/rtabmap.git src/rtabmap
git clone --branch ros2 https://github.com/introlab/rtabmap_ros.git src/rtabmap_ros
colcon build

**Comment by nima-negarandeh** [comment]
> @NimaNGRD I am using Nvidia Xavier AGX.
> I am also getting that error. But I believe that is because T265 node is not running. So "doom" is used to create the transformation for the D435 camera.
> 
> Have you already installed rtabmap and rtabmap_ros?
> 
> I am getting into some trouble while compiling it.
> 
> @jdgalviss Do you have a tutorial showing how you install, build and launch everything?

I'm not sure.
When I run
`ros2 run realsense_ros2 rs_t265_node`
at least I can read the IMU data, but not the Odometry data.

I didn't install and the rtabmap. Because, honestly, I wanted to move step by step and solve the issues.
But, I installed the cartographer using the following line:
`sudo apt install ros-foxy-cartographer*`  
As soon as the cartographer works, I would try to install the rtabmap package and I would update you.

**Comment by nima-negarandeh** [comment]
> > Hello @MarcoAndrade26,
> > Thank you so much. Your solution solved the problem and the package was built successfully.
> > However, I reached a warning when I try to run
> > `ros2 run realsense_ros2 rs_d435_node --ros-args -p is_color:=true -p publish_depth:=true -p fps:=30`
> > or the following launch files that include the D435 camera.
> > Could you run all the nodes without any problem?
> > Do you also use Jetson Nano? If yes, I appreciate it if you tell me the version of librealsense SDK that you are using.
> 
> I am using Intel Realsense Viewer v2.48.0
> 
> This is what I used to install it.
> 
> `git clone -b debian/foxy/focal/librealsense2 https://github.com/IntelRealSense/librealsense2-release`
> `mkdir build && cd build`
> `cmake ../ -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=true -DBUILD_GRAPHICAL_EXAMPLES=true -DBUILD_WITH_CUDA=true`
> `sudo make uninstall && make clean && make && sudo make install`
> `sudo cp config/99-realsense-libusb.rules /etc/udev/rules.d/`
> `sudo apt-get install ros-foxy-realsense2-camera ros-foxy-realsense2-description -y`
> `sudo apt install openjdk-8-jdk`
> 
> If you want, send me a whatsapp: +52 55 4834 8535

Thanks a lot for sharing the information.
Actually, I have some questions and I would reach you via Whatsapp as soon as I come back home.

**Comment by nima-negarandeh** [comment]
> > Hello @jdgalviss,
> > Thank you for your response.
> > When I try to run the following node, I recieve warnings and cannot see any of topics in rviz2.
> > `~/real_ws$ ros2 run realsense_ros2 rs_d435_node --ros-args -p is_color:=true -p publish_depth:=true -p fps:=15
> > starting rs_d435 node
> > [INFO] [1630235712.690903191] [D435Node]: Device set up
> > [INFO] [1630235712.691156946] [D435Node]:
> > Module name: Stereo Module
> > [INFO] [1630235712.730648231] [D435Node]:
> > Module name: RGB Camera
> > [INFO] [1630235712.777563262] [D435Node]: RGB Camera stream is enabled - width: 640, height: 480, fps: 15
> > [INFO] [1630235713.174500408] [D435Node]: Capture Pipeline started!
> > Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> > at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> > Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> > at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> > Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> > at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> > Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> > at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> > Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> > at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> > Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> > at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> > Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> > at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> > Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> > at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> > Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> > at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> > Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> > at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> > Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> > at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> > Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> > at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp
> > Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist
> > at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp`
> > Actually, this issue appers in all the launch files that involve the D435 camera.
> > Would you please help me with this problem?
> 
> @NimaNGRD The reason why you are getting this warning is that I did this repo specifically tailored to one project I was developing in which I needed to make sure the transform odom->base_link was available before publishing anything. The easy workaround to this is to comment this line on the rs_d435_node.cpp file:
> 
> // while (!tf_buffer_.canTransform("odom", "base_link", tf2::TimePointZero, 10s))
> // {
> // };
> 
> I will push this modification to master because it makes more sense for anyone who wants to use the code.
> 
> @MarcoAndrade26 I haven't tested rtabmap in a while so there is a chance the integration is broken. I will have a look in the next days. But initially, I just followed the indications in the official ros2 repo. It didn't work very well on the Jetson Nano if I remember well. The results you see in this repo were obtained by recording a rosbag and then running rtabmap on a PC. I hope that helps.
> 
> If you find anything that needs to be modified, feel free to create a PR and I will review it as soon as I can.

Thanks for the update
It solved the warning and now it doesn't get stuck in the loop.
But, I still cannot read topics from the D435 camera or visualize them in rviz2.

```
~/real_ws$ rviz2 
[INFO] [1630296617.093901288] [rviz2]: Stereo is NOT SUPPORTED
[INFO] [1630296617.094314986] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[INFO] [1630296617.193412954] [rviz2]: Stereo is NOT SUPPORTED
qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3166, resource id: 12589758, major code: 40 (TranslateCoords), minor code: 0
[INFO] [1630296627.163695086] [rviz2]: Stereo is NOT SUPPORTED
[INFO] [1630296627.887094565] [rviz]: Message Filter dropping message: frame 'camera_link_d435' at time 1630296627.175 for reason 'Unknown'
[INFO] [1630296627.938117169] [rviz]: Message Filter dropping message: frame 'camera_link_d435' at time 1630296627.242 for reason 'Unknown'
[INFO] [1630296628.002049304] [rviz]: Message Filter dropping message: frame 'camera_link_d435' at time 1630296627.308 for reason 'Unknown'
[INFO] [1630296628.066855086] [rviz]: Message Filter dropping message: frame 'camera_link_d435' at time 1630296627.376 for reason 'Unknown'
[INFO] [1630296628.130076388] [rviz]: Message Filter dropping message: frame 'camera_link_d435' at time 1630296627.442 for reason 'Unknown'
[INFO] [1630296628.194051596] [rviz]: Message Filter dropping message: frame 'camera_link_d435' at time 1630296627.509 for reason 'Unknown'
[INFO] [1630296628.258083367] [rviz]: Message Filter dropping message: frame 'camera_link_d435' at time 1630296627.575 for reason 'Unknown'
[INFO] [1630296628.322000138] [rviz]: Message Filter dropping message: frame 'camera_link_d435' at time 1630296627.642 for reason 'Unknown'
[INFO] [1630296628.386141179] [rviz]: Message Filter dropping message: frame 'camera_link_d435' at time 1630296627.709 for reason 'Unknown'
[INFO] [1630296628.482407898] [rviz]: Message Filter dropping message: frame 'camera_link_d435' at time 1630296627.776 for reason 'Unknown'
```

![photo_2021-08-30](https://user-images.githubusercontent.com/76465644/131288409-9d02ff9c-9195-449e-aa48-445ecca522e7.jpg)

@jdgalviss, do you have any suggestions?

**Comment by jdgalviss** [comment]
> > > Hello @jdgalviss,
> > > Thank you for your response.
> > > When I try to run the following node, I recieve warnings and cannot see any of topics in rviz2.
> > > `~/real_ws$ ros2 run realsense_ros2 rs_d435_node --ros-args -p is_color:=true -p publish_depth:=true -p fps:=15 starting rs_d435 node [INFO] [1630235712.690903191] [D435Node]: Device set up [INFO] [1630235712.691156946] [D435Node]: Module name: Stereo Module [INFO] [1630235712.730648231] [D435Node]: Module name: RGB Camera [INFO] [1630235712.777563262] [D435Node]: RGB Camera stream is enabled - width: 640, height: 480, fps: 15 [INFO] [1630235713.174500408] [D435Node]: Capture Pipeline started! Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp Warning: Invalid frame ID "odom" passed to canTransform argument target_frame - frame does not exist at line 133 in /tmp/binarydeb/ros-foxy-tf2-0.13.10/src/buffer_core.cpp`
> > > Actually, this issue appers in all the launch files that involve the D435 camera.
> > > Would you please help me with this problem?
> > 
> > 
> > @NimaNGRD The reason why you are getting this warning is that I did this repo specifically tailored to one project I was developing in which I needed to make sure the transform odom->base_link was available before publishing anything. The easy workaround to this is to comment this line on the rs_d435_node.cpp file:
> > // while (!tf_buffer_.canTransform("odom", "base_link", tf2::TimePointZero, 10s))
> > // {
> > // };
> > I will push this modification to master because it makes more sense for anyone who wants to use the code.
> > @MarcoAndrade26 I haven't tested rtabmap in a while so there is a chance the integration is broken. I will have a look in the next days. But initially, I just followed the indications in the official ros2 repo. It didn't work very well on the Jetson Nano if I remember well. The results you see in this repo were obtained by recording a rosbag and then running rtabmap on a PC. I hope that helps.
> > If you find anything that needs to be modified, feel free to create a PR and I will review it as soon as I can.
> 
> Thanks for the update
> It solved the warning and now it doesn't get stuck in the loop.
> But, I still cannot read topics from the D435 camera or visualize them in rviz2.
> 
> ```
> ~/real_ws$ rviz2 
> [INFO] [1630296617.093901288] [rviz2]: Stereo is NOT SUPPORTED
> [INFO] [1630296617.094314986] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
> [INFO] [1630296617.193412954] [rviz2]: Stereo is NOT SUPPORTED
> qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 3166, resource id: 12589758, major code: 40 (TranslateCoords), minor code: 0
> [INFO] [1630296627.163695086] [rviz2]: Stereo is NOT SUPPORTED
> [INFO] [1630296627.887094565] [rviz]: Message Filter dropping message: frame 'camera_link_d435' at time 1630296627.175 for reason 'Unknown'
> [INFO] [1630296627.938117169] [rviz]: Message Filter dropping message: frame 'camera_link_d435' at time 1630296627.242 for reason 'Unknown'
> [INFO] [1630296628.002049304] [rviz]: Message Filter dropping message: frame 'camera_link_d435' at time 1630296627.308 for reason 'Unknown'
> [INFO] [1630296628.066855086] [rviz]: Message Filter dropping message: frame 'camera_link_d435' at time 1630296627.376 for reason 'Unknown'
> [INFO] [1630296628.130076388] [rviz]: Message Filter dropping message: frame 'camera_link_d435' at time 1630296627.442 for reason 'Unknown'
> [INFO] [1630296628.194051596] [rviz]: Message Filter dropping message: frame 'camera_link_d435' at time 1630296627.509 for reason 'Unknown'
> [INFO] [1630296628.258083367] [rviz]: Message Filter dropping message: frame 'camera_link_d435' at time 1630296627.575 for reason 'Unknown'
> [INFO] [1630296628.322000138] [rviz]: Message Filter dropping message: frame 'camera_link_d435' at time 1630296627.642 for reason 'Unknown'
> [INFO] [1630296628.386141179] [rviz]: Message Filter dropping message: frame 'camera_link_d435' at time 1630296627.709 for reason 'Unknown'
> [INFO] [1630296628.482407898] [rviz]: Message Filter dropping message: frame 'camera_link_d435' at time 1630296627.776 for reason 'Unknown'
> ```
> 
> ![photo_2021-08-30](https://user-images.githubusercontent.com/76465644/131288409-9d02ff9c-9195-449e-aa48-445ecca522e7.jpg)
> 
> @jdgalviss, do you have any suggestions?

From what I see, you haven't added any topics to rviz.
